package tsar.alex.utils;

public class CommonTextConstants {
    public static final String ALREADY_REGISTERED = "Пользователь с таким именем уже зарегистрирован!";
    public static final String WRONG_LOGIN_OR_PASSWORD = "Неверный логин или пароль.";
    public static final String NO_GAME = "Игра с gameId = %s не найдена.";
    public static final String NO_ACTIVE_GAME = "Игра с gameId = %s не существует или уже завершена.";
    public static final String ALREADY_SEARCHING = "Вы уже ищите игру (возможно, из другой вкладки или с другого устройства).";
    public static final String ALREADY_IN_GAME = "Вы уже в игре с gameId = %s";
    public static final String ALREADY_SUBSCRIBED = "Вы уже подключены к игре (возможно, из другой вкладки или с другого устройства).";
    public static final String SERVICE_UNAVAILABLE = "Данный сервис временно недоступен. Пожалуйста, попробуйте позже.";
    public static final String CANNOT_FIND_ENEMY = "Не можем подобрать противника для вас. Похоже, сейчас никто кроме вас не хочет играть =( Пожалуйста, попробуйте позже.";
    public static final String INCORRECT_GAME_ID = "Некорректный gameId.";
    public static final String SERVER_ERROR = "На сервере что-то сломалось. Когда-нибудь мы это починим.";

    public static final String BAD_MOVE = "Bad move.";
    public static final String CANNOT_UNSUBSCRIBE = "User with username = %s and sessionId = %s tried to unsubscribe ChessGame websocket.";
    public static final String CHESS_MOVE_NULL = "chessMove is null.";
    public static final String DB_AND_RAM_OBJECT_NOT_CORRESPOND_FINISHED = "game with gameId = %s has status \"finished\" in game DB, but not in chessGameWebsocketRoomsHolder.";
    public static final String DB_AND_RAM_OBJECT_NOT_CORRESPOND_ID = "game DB contains game with gameId = %s, but chessGameWebsocketRoomsHolder doesn't.";
    public static final String DB_AND_RAM_OBJECT_NOT_CORRESPOND = "Objects in DB (%s) and in RAM (%s) not correspond.";
    public static final String ERROR_CODE = "errorCode";
    public static final String EXPIRED = "Refresh token is expired.";
    public static final String GAME_BEING_CREATED = "Can't cancel. Game is already being created.";
    public static final String GAME_FINISHED = "The game is already finished.";
    public static final String GAME_ID_NOT_FOUND = "No rating record was found for match with gameId: %s.";
    public static final String GAME_ID_NULL = "gameId must not be null.";
    public static final String GAME_TYPE = "gameType";
    public static final String HEADER_NOT_PRESENT_OR_INCORRECT = "%s header is not present or has incorrect value.";
    public static final String INCORRECT_CHESS_PIECE_CLASS = "Incorrect chessPieceClass = %s.";
    public static final String INCORRECT_GAME_TYPE = "Incorrect ChessGameType value.";
    public static final String INCORRECT_JSON = "Unable to parse incoming JSON. Incorrect incoming JSON object.";
    public static final String INCORRECT_WEBSOCKET_CONTENT = "Incorrect websocket message content type. Expected content type is JSON.";
    public static final String MULTIPLE_ACTIVE_GAMES = "Several active games were found for user with username = %s. gameIds = [%s].";
    public static final String NO_EXCEPTION_CODE = "Websocket exception code can't be null!";
    public static final String NO_GAME_ID_HEADER = "No Game-Id header.";
    public static final String NO_USER_RATING = "No rating was found for username = %s and chessGameType = %s.";
    public static final String NOT_SUBSCRIBED = "You are not subscribed to game with gameId = %s.";
    public static final String NOT_YOUR_TURN = "It's not your turn.";
    public static final String OBJECT_HAS_ERRORS = "%s has the following errors = [%s].";
    public static final String RATINGS_STATUS_MISMATCH = "Ratings for user with username = %s are initialized according to auth_db, but they actually are not according to matcher_db.";
    public static final String REFRESH_TOKEN_BLANK = "refresh-token cookie is blank.";
    public static final String REFRESH_TOKEN_COOKIE_NAME = "refresh-token";
    public static final String REFRESH_TOKEN_NOT_FOUND = "Refresh token not exist or expired.";
    public static final String SESSION_NOT_FOUND = "WebsocketSessionMap doesn't contain session with sessionId = %s.";
    public static final String UNAUTHORIZED = "Unauthorized.";
    public static final String UNEXPECTED_OBJECT_CLASS = "Variable %s referenced the object with unexpected class = %s.";
    public static final String INCORRECT_RESPONSE = "Incorrect http response body object content = %s.";
    public static final String UNKNOWN_ERROR = "Unknown server error.";
    public static final String UNREGISTERED_USER_AUTHENTICATED = "User with username = %s was authenticated on the Matcher microservice, but they are not in app_user table of auth_db.";
    public static final String USER_NOT_FOUND = "There is no registered user with username = %s.";
    public static final String WRONG_PASSWORD = "Password is wrong.";
    public static final String X_AUTHORIZATION = "X-Authorization";
    public static final String UNEXPECTED_HTTP_STATUS = "Unexpected http status code = %s.";
    public static final String UNAVAILABLE_SERVICE = "Cannot send http request to %s microservice, because it is unavailable right now.";
    public static final String NO_RATINGS_RECORD_FOR_GAME_ID = "No chessGameUserRatingsRecord found for game with gameId = %s.";
    public static final String ILLEGAL_ARGUMENT = "Illegal %s value = %s.";
    public static final String RATINGS_NOT_CORRESPOND = "Initial user ratings in currentUserRating (%d) and in gameUsersRatingsRecord (%d) for game with gameId = %s are not equal.";
    public static final String INCORRECT_HTTP_OK_RESPONSE_OBJECT = "Incorrect %s object. Constraint violations = [%s].";

    public static final String ALREADY_REGISTERED_LOG = "User with username = %s is already registered.";
    public static final String RATINGS_INITIALIZED_LOG = "Ratings were initialized for user with username = %s.";
    public static final String RATINGS_NOT_INITIALIZED_LOG = "Ratings were not initialized for user with username = %s.";
    public static final String RATINGS_ALREADY_INITIALIZED_LOG = "Ratings were already initialized for user with username = %s (at least for chessGameType = %s).";
    public static final String WEBSOCKET_DISCONNECT_LOG = "Websocket disconnect event. sessionId = %s.";
    public static final String WEBSOCKET_CONNECTED_LOG = "Websocket connection was established. sessionId = %s.";
    public static final String ALREADY_NOT_SEARCHING_LOG = "Nothing to cancel/abort: there is no uwfg object with username = %s in map of users waiting for game.";
    public static final String RESPONSE_BODY_NULL_LOG = "Http response body is null. Must be not null %s object.";
    public static final String MICROSERVICE_AVAILABLE_LOG = "%s microservice became available.";
    public static final String MICROSERVICE_UNAVAILABLE_LOG = "%s microservice became unavailable.";
    public static final String TECHNICAL_FINISH_LOG = "Technical finish for game with gameId = %s.";
    public static final String OBJECT_BEFORE_UPDATE_LOG = "%s before update = %s.";
    public static final String OBJECT_AFTER_UPDATE_LOG = "%s after update = %s.";
    public static final String NO_OPENED_SESSION_LOG = "uwfg object for user with username = %s is in map of users waiting for game, but websocket session is absent or closed.";
    public static final String NO_RATING_FOR_USER_AND_GAME_TYPE_LOG = "User with username = %s has no initialized rating for chessGameType = %s and tries to search for game.";
    public static final String UWFG_MAP_BEFORE_REMOVE_LOG = "uwfgMap before removing entries = %s.";
    public static final String UWFG_MAP_AFTER_REMOVE_LOG = "uwfgMap after removing entries = %s.";
    public static final String REMOVED_ENTRIES_LOG = "Removed entries = %s.";
    public static final String DIFFERENT_SESSION_IDS = "sessionId to remove = %s, sessionId from uwfgMap = %s.";
    public static final String BAD_ENEMY_RESULT_LOG = "Bad enemy personal result for user with username = %s.";
    public static final String DISCONNECT_TASK_UPDATED_LOG = "Timeout disconnect task was updated for user with username = %s.";
    public static final String UWFG_MAP_BEFORE_START_GAMES_LOG = "gameType = %s, uwfgMap = %s.";
    public static final String UWFG_LIST_TO_START_GAMES_LOG = "gameType = %s, uwfgList = %s.";
    public static final String PRELIMINARY_AVAILABILITY_STATUS_LOG = "Before request Game master availability status = %b.";
    public static final String USER_ACTIVE_GAMES_LOG = "User with username = %s is currently in the following games = %s.";
    public static final String WEBSOCKET_REQUEST_HANDLING_EXCEPTION_LOG = "Exception occurred during websocket request handling. SessionId = %s, exception = %s.";

}
