DROP TABLE IF EXISTS refresh_token;
DROP TABLE IF EXISTS app_user;


CREATE TABLE app_user (
    username VARCHAR(50) PRIMARY KEY,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    rating_initialized BOOLEAN NOT NULL
);

CREATE TABLE refresh_token (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token_value VARCHAR NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    username VARCHAR(50) NOT NULL REFERENCES app_user(username) ON DELETE CASCADE
);